version: '3.8'

services:
  api:
    build: .
    ports:
      - "8001:8001"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - DATABASE_NAME=leilao_insights
      - ENVIRONMENT=development
    depends_on:
      - mongodb
    volumes:
      - .:/app
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8001 --reload

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 