version: '3.8'

services:
  api:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DB=leilao_insights
      - LOG_LEVEL=INFO
      - LOG_FILE=app.log
    depends_on:
      - mongodb
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=leilao_insights

volumes:
  mongodb_data: 